### ISSUE TITLE
Eigener Hintergrund

### ISSUE THREAD

**Issue by necrome** [EQdkpPlus/template-eqdkp_bluesky#2]
Hi!

Wenn man einen eigenen Hintergrund einfügen will, dann wird dieser nicht geändert. Bleibt der Standard-Hintergrund vom Style

**Comment by Asitara** [comment]
Meep, hmm habe grad aus Zeit und Entwicklungsgründen keine aktuelle v2.0.1 laufen. Kann mir das aber nicht wirklich erklären wieso das nicht gehen sollte.
Wie lautet dein Pfad zum Bild, ist dieser relativ oder absolut? ..es kann passieren das EQdkp die Datei nicht finden kann und lädt daraufhin den Fallback (Style default bzw. Game Bild). Vom Style her kann ich jedenfalls kein Fehler sehen.

**Comment by necrome** [comment]
Hab die Pics (hab mehrere versucht) auf den FTP geladen und dann per auswahlbutton ausgewählt. dann wurde die komplette adresse (http://domain.de/path/image.jpg bzw. png) da eingespeichert.

**Comment by Asitara** [comment]
So bin mal eben auf deiner Seite gewesehn um zuschauen ob und was in der Konsole steht,... scheint doch alles zufunzen?!
http://vu2056.cloudserv3.menkisys.de/eqdkp/data/8d37590f6c2c2007fa320b22c2fd983c/files/system/warlords-of-draenor-release-date-cinematic1-640x330.jpg
Ist dein angegebenes Bild und wird auch so dargestellt, probier mal dein browser cache zulöschen.. ich kann jedenfalls kein Fehler sehen. Da ist zwar ne kleine unschöneit vom Code her aber das Bild wird geladen und angezeigt.

**Comment by necrome** [comment]
Ja komischerweise hat es plötzlich ohne cache löschen funktioniert...
trotzdem danke!
Am 29.04.2015 15:26 schrieb "Asitara" <notifications@github.com>:
