### ISSUE TITLE
Chat überschreibt sich

### ISSUE THREAD

**Issue by necrome** [EQdkpPlus/template-eqdkp_bluesky#3]
Hi!

Mir ist aufgefallen, dass sich die Chateingabe überschreibt 
![chat](https://cloud.githubusercontent.com/assets/12144263/7417347/d8f58854-ef65-11e4-8d10-6a3bc3c8cd40.png)

**Comment by Asitara** [comment]
Joa, kann gut sein.. sind bisweilen nicht dazu gekommen die ganzen Plugins an alle Styles anzupassen.
Aber komisch sieht es schon aus, theoretisch hätte das so nicht aussehen dürfen selbst bei falschem code^^
..Naja ich werds mir nachher mal anschauen und ggf fixen.
